site_name: Autolabel
site_url: https://refuel.ai
repo_url: https://github.com/refuel-ai/autolabel
repo_name: refuel-ai/autolabel

nav:
  - Guide:
    - Introduction: index.md
    - Getting Started: guide/overview/getting-started.md
    - Tutorial - Toxic comment classification: guide/overview/tutorial-classification.md
    - Models:
      - LLMs: guide/llms/llms.md
    - Labeling Tasks:
      - Classification Task: guide/tasks/classification_task.md
      - Question Answering Task: guide/tasks/question_answering_task.md
      - Entity Matching Task: guide/tasks/entity_matching_task.md
    - Improving Labeling Accuracy:
      - Prompting Better: guide/accuracy/prompting-better.md
      - Example Selection: guide/accuracy/example-selection.md
      - Confidence: guide/accuracy/confidence.md
      - Chain of Thought: guide/accuracy/chain-of-thought.md
    - Reliability and Robustness:
      - LLM Output Caching: guide/reliability/llm-output-caching.md
      - State Management: guide/reliability/state-management.md
    - Working with Autolabel configs:
      - Overview: guide/configs/overview.md
  - Concepts: concepts/concepts.md
  - Reference:
      - AutoLabeler: reference/labeler.md
      - Config: reference/configs.md
      - Models: reference/models.md
      - Tasks: reference/tasks.md
      - Schema: reference/schema.md
      - Cache: reference/cache.md
      - Example Selector: reference/example_select.md
      - Data Models: reference/data_models.md

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo

plugins:
  - mkdocstrings
  - search
  - mkdocs-jupyter
  - table-reader

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
