site_name: AutoLabel
site_url: https://refuel.ai
repo_url: https://github.com/refuel-ai/refuel-oracle
repo_name: refuel-ai/refuel-oracle

nav:
  - Getting Started: index.md
  - Modules: modules.md
  - Reference: api.md
  - Examples: example_banking.ipynb

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo

plugins:
  - mkdocstrings
  - search
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
