name: Ruff Format
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/ruff-action@v1
        with:
          args: "check --output-format=github"
          changed-files: "true"
